[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$tta6l1KK8V4LQWgNwbg35g$9mhpbqtn3da0YTDlD2reKww7cVlhnuUGHzeiCb9Mg8YDcxOmaS9OKheqWWDAw0ume72U4C2RgD7mxn0prEezYg
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
logfile = /var/lib/odoo/odoo-server.log
log_level = info
workers = 0
limit_time_cpu = 600
limit_time_real = 1200
max_cron_threads = 1

